### ISSUE TITLE
build failure against ghc-8.10: src/TypeFun/Data/List.hs:116:12: error:  Cannot instantiate unification variable ‘b1’

### ISSUE THREAD

**Issue by trofi** [s9gf4ult/type-fun#4]
`ghc-8.10` fails to build `type-fun` as:

```
Building library for type-fun-0.1.2..
[5 of 5] Compiling TypeFun.Data.List ( src/TypeFun/Data/List.hs, dist/build/TypeFun/Data/List.o, dist/build/TypeFun/Data/List.dyn_o )

src/TypeFun/Data/List.hs:116:12: error:
    • Cannot instantiate unification variable ‘b1’
      with a type involving polytypes:
        proxy l -> ((l ~ (l :++: '[])) => r) -> r
        GHC doesn't yet support impredicative polymorphism
    • In the expression: unsafeCoerce id
      In an equation for ‘appendId’: appendId = unsafeCoerce id
    • Relevant bindings include
        appendId :: proxy l -> ((l ~ (l :++: '[])) => r) -> r
          (bound at src/TypeFun/Data/List.hs:116:1)
    |
116 | appendId = unsafeCoerce id
    |            ^^^^^^^^^^^^^^^
```

**Comment by markus1189** [comment]
Noticed this as well, because for example `telegram-raw-api` does not build on 8.10 due to `type-fun`...

I honestly have no idea how to fix this though :sweat_smile:
